### ISSUE TITLE
fsh-trip: Configuration missing required property: status

### ISSUE THREAD

**Issue by patrick-werner** [FHIR/GoFSH#164]
When using GoFSH with the fshing-trip feature gofsh/sushi-config.yaml is missing the status property, leading to an error:

```
error Configuration missing required property: status
  File: gofsh/sushi-config.yaml
```
Expected behaviour: status is set by fsh-trip

**Comment by jafeltra** [comment]
Once the next version of SUSHI is released (it is TBD when that will be released, but it shouldn't be too far in the future) and that version is integrated into GoFSH (usually shortly after the SUSHI release), this warning should go away.
