### ISSUE TITLE
r3 Exclusive dependency

### ISSUE THREAD

**Issue by Republicof1** [FHIR/GoFSH#183]
When running against FHIR 3.0.2 definitions using '-d hl7.fhir.r3.core@3.0.2' both r3 and the default r4 - v4.0.1 are loaded and used. This seems to cause failures related to differences between the r3 and r4 StructureDefinition.

I think the following (processing.ts:ln120-122 is responsible
```
 if (!dependencies.some(dep => /hl7\.fhir\.r(4|5|4b)\.core/.test(dep))) {
    dependencies.push('hl7.fhir.r4.core@4.0.1');
  }
```
Could this case be added for r3 please?

**Comment by cmoesel** [comment]
Hi @Republicof1.  Unfortunately, GoFSH and SUSHI support only FHIR R4 and above.  Some of the primary elements in `StructureDefinition` (e.g., `type`) are different between FHIR R3 and FHIR R4, and GoFSH is designed to work w/ the R4 (and above) representation.

We currently have no plans to support R3, but will take a note to make it more clear that only FHIR R4 and above are supported.  Sorry...

**Comment by Republicof1** [comment]
Ah okay, thanks for coming back to me with this!
