### ISSUE TITLE
run gofsh -s file-per-definition got "Unexpected error: The "path" argument must be of type string. Received undefined"

### ISSUE THREAD

**Issue by mduna** [FHIR/GoFSH#192]
Steps:
1. download US Core Implementation Guild 4.0.0 STU4 Release package
2. unzip the package to a directory
3. go the package directory run commend "gofsh -s file-per-definition"
4. got the error. 

C:\Sushi\package>gofsh -s file-per-definition
info  Starting goFSH v1.6.1 (implements FHIR Shorthand specification v2.0.0)
info  Arguments:
info    --style file-per-definition
(node:18704) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18704) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(node:18704) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(node:18704) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
error Unexpected error: The "path" argument must be of type string. Received undefined

The node version:
C:\Sushi\package>node --version
v16.15.0

Could you please help, what I did wrong? I am very new, follow the steps in Mark Kramer's presentation on 2021 June DevDays. I like to use Fish shorthand to update an existing IG. Thanks.

**Comment by cmoesel** [comment]
Hi @mduna.  Thanks for reporting this.  It seems that version 1.6.1 broke the default path argument (which worked fine in version 1.6.0).  We'll have to fix that.

For now, you will need to specify the folder you want to run GoFSH on.  So, if you want to do file-per-definition, then your command should look like this:
```
gofsh /path/to/fhir/project -s file-per-definition
```

If you're already in the folder you want to convert (as you noted above), then you can use `.` as the path to say "run GoFSH here", like this:
```
gofsh . -s file-per-definition
```

**Comment by mduna** [comment]
Hi Chris, 
By following your instruction, it works!
Thanks,
Ming
