### ISSUE TITLE
Support FSH 3.0 CodeableReference keyword

### ISSUE THREAD

**Issue by cmoesel** [FHIR/GoFSH#237]
GoFSH should support the new CodeableReference keyword for [add element rules](https://hl7.org/fhir/uv/shorthand/2023Sep/reference.html#add-element-rules) and [type rules](https://hl7.org/fhir/uv/shorthand/2023Sep/reference.html#type-rules).

**Comment by jafeltra** [comment]
It appears this has been completed, possibly as part of #229.
