### ISSUE TITLE
French ICD-10 CodeSystem not usable with Sushi after goFSH

### ISSUE THREAD

**Issue by davidouagne** [FHIR/GoFSH#245]
Hello,

I used goFSH from a JSON CodeSystem resource, but the result is not usable with Sushi.

I am attaching the resources that will allow you to reproduce the bug.

I use goFSH 2.1.2, sushi 3.4.0 and nodejs 20.8.0 or 18.15.0.

[CodeSystem-terminologie-cim-10.zip](https://github.com/FHIR/GoFSH/files/12804917/CodeSystem-terminologie-cim-10.zip)

Best regards,

**Comment by cmoesel** [comment]
Thank you for reporting this. We'll take a look at it!
