### ISSUE TITLE
Resolve URL for ValueSets and CodeSystems that must be represented as Instances

### ISSUE THREAD

**Issue by mint-thompson** [FHIR/GoFSH#264]
Transferred from internal JIRA issue originally created 2021-11-09.

When resolving a URL, if that URL corresponds to a ValueSet or CodeSystem, GoFSH checks to make sure that the resource can be represented in FSH as a ValueSet or CodeSystem (as opposed to an Instance of one of those types). Because SUSHI can now fish up Instances of ValueSets and CodeSystems when one of those resources is needed, GoFSH should allow such resources to have their URLs resolved.

**Comment by jafeltra** [comment]
We don't fully understand what this issue is looking for, but we are not aware of any problems related to resolving to URLs for ValueSets and CodeSystems.
