### ISSUE TITLE
Missing SD conversions

### ISSUE THREAD

**Issue by jvitrifork** [FHIR/GoFSH#75]
GoFSH'ing on https://github.com/hl7dk/dk-core/tree/master/input/resources results in only 3 converted resources: one instance, a codesystem and a valueset. How far down in the backlog of GoFSH would it be to successfully convert more of the resources within such an IG (that contains a single resource SD and an couple of datatype SD's)?

**Comment by cmoesel** [comment]
Hi @jvitrifork -- thanks for reporting this.  Looking at the repository link you provided, I think the main issue is that GoFSH currently only reads in JSON files; but `dk-core` contains many XML files as well.  We're currently working on a GoFSH 1.0 release that would be feature-complete for JSON definitions; but hadn't yet scheduled support for XML.  That said, we can look into it to see how difficult it would (or wouldn't) be to slip in XML support.

One possible workaround is to run the IG Publisher on your project first and then point GoFSH at the generated `output` folder, which I _think_ should contain JSON definitions for everything.  But if you're not in a big time crunch, you might want to wait for GoFSH 1.0.

**Comment by jvitrifork** [comment]
Thx for the advise @cmoesel  - sure, the output folder contains the files in json format. Trace is the following, which implies an actual bug I believe:

```
output % gofsh . -l debug
info  Starting goFSH v0.4.0 (implements FHIR Shorthand specification v0.13.x)
info  Using input directory: .
info  Found 32 JSON files.
debug Skipping non-FHIR JSON file: canonicals.json
debug Skipping non-FHIR JSON file: package.manifest.json
debug Skipping non-FHIR JSON file: qa.json
debug Skipping non-FHIR JSON file: usage-stats.json
info  Checking local cache for hl7.fhir.r4.core#4.0.1...
info  Found hl7.fhir.r4.core#4.0.1 in local cache.
info  Loaded package hl7.fhir.r4.core#4.0.1
info  Using output directory: gofsh
(node:84693) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:84693) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
warn  InstanceOf definition not found for episodeOfCare-example-wrong. The ResourceType of the instance will be used as a base.
warn  InstanceOf definition not found for episodeOfCare-example. The ResourceType of the instance will be used as a base.
debug Loaded 19 optimizers from /usr/local/lib/node_modules/gofsh/dist/optimizer/plugins
debug Running optimizer simplify_mapping_names: Simplify Mapping names by removing the appended source information from the name (where possible)
debug Running optimizer resolve_value_set_component_rule_urls: Replace URLs in value set rules with their names or aliases
error Could not use input directory: Cannot read property 'match' of undefined
```

**Comment by jvitrifork** [comment]
output directory is obtained by simply running the publisher on the IG ```java  -jar publisher.jar -ig ig.ini```

**Comment by cmoesel** [comment]
Darn.  We'll take a look!

**Comment by cmoesel** [comment]
I managed to find and fix the issue that caused SUSHI to exit early when running against the IG `output` directory.  So this should be fixed in the next release (tentatively scheduled for Monday).  We're also looking at what it might look like to support XML input.

**Comment by jvitrifork** [comment]
FYI @tmh-mjolner

**Comment by cmoesel** [comment]
I'm closing this issue as GoFSH 1.0.0 was released with the fix for the identified bug as well as support for XML.
